variables: secret.yml
templates:
  tv:
    exists_series:
      - '/plex-media/Tv Shows/English/{{ series_name }}'
      - '{? path.download ?}'
    thetvdb_lookup: yes
    inputs: 
      - rss: http://showrss.info/user/32768.rss?magnets=true&namespaces=true&name=null&quality=anyhd&re=yes
    set:
      propers: yes
      skip_files:
        - '*.nfo'
        - '*[sS]ample*'
        - '*.txt'
      move_completed_path: '{? path.tv ?}'
      content_filename: '/{{ series_name }} - {{ series_id }}'
    all_series: yes
  movie:
    proper_movies: yes
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}                    # Block any subbed/dubbed/etc videos
        - \bspanish\b: {from: title}                          # Spanish releases kept cropping up
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title} # Block series, only accept one at a time
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bR5\b: {from: title}                               # The following are poor quality types that somehow got through the quality
        - \bWEBSCR\b: {from: title}                           # features usually due to the title including a keyword like "720p" as well
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}                              # The following are groups with poor quality releases
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \[facepalm\]: {from: title}
        - \bASAP\b: {from: title}   
        - \bHDTC\b: {from: title}
        - \bHC\b: {from: title}
        - \bCHINESE\b: {from: title}
        - \bGERMAN\b: {from: title}
        - \bITALIAN\b: {from: title}
        - \bJAPANESE\b: {from: title}
        - \bSWEDISH\b: {from: title}
        - \bWEBRip\b: {from: title}
        - \bWEB-DL\b: {from: title}
    seen_movies: 
      scope: local
    inputs:
       - rss: https://rarbg.to/rssdd_magnet.php?category=44
    set:
      move_completed_path: '{? path.movie ?}'
      content_filename: '/{{movie_name}} ({{movie_year}}) [{{quality.resolution}}]'
    quality:
      - 1080p
      - '!10bit'
  imdb-movie:
    require_field: imdb_url
    imdb:
      min_score: 5.9
      min_votes: 2500
      min_year: 2016
      reject_genres:
        - musical
  global:
    # Require at least 10 seeds of any torrent
    verify_ssl_certificates: no
    free_space:
      path: /plex-media
      space: 50000
    pathscrub: windows
    transmission:
      main_file_only: yes
      username: transmission
      password: '{? deluge.password ?}'
      host: localhost
      port: 9091
      path: '/home/maxime/Downloads/'
      include_subs: yes
      magnetization_timeout: 30
    regexp:
      reject:
        - \btrailer\b: {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
      reject:
        - '*.wmv'
        - '*CD1*'
        - '*.rar'
        - '*.r0*'
    torrent_alive:
      min_seeds: 10 
    retry_failed:
      max_retries: 10
      retry_time: 1 hour
      retry_time_multiplier: 2
tasks:
  tv-show:
    verify_ssl_certificates: no
    template:
      - global
      - tv
  movie-dl:
    template:
      - global
      - imdb-movie
      - movie
web_server: 7575
