variables: secret.yml
templates:
  tv:
    exists_series:
      - '/home/maxime/media/Tv Shows/English/{{ tvdb_series_name }}'
      - '/home/maxime/media/Downloads/'
    thetvdb_lookup: yes
    inputs: 
      - rss: http://showrss.info/user/32768.rss?magnets=true&namespaces=true&name=clean&quality=hd&re=yes
    set:
      propers: yes
      skip_files:
        - '*.nfo'
        - '*[sS]ample*'
        - '*.txt'
      movedone: '/home/maxime/media/Tv Shows/English/{{ series_name }}/Season {{series_season}}/'
      content_filename: '/{{ series_name }} - {{ series_id }}'
    all_series: yes
    series:
      - "Marvel's Agents of S.H.I.E.L.D.":
          name_regexp: ^marvel(')?s.agents.of.(s.h.i.e.l.d.?|shield)
  movie:
    proper_movies: yes
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}                    # Block any subbed/dubbed/etc videos
        - \bspanish\b: {from: title}                          # Spanish releases kept cropping up
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title} # Block series, only accept one at a time
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bR5\b: {from: title}                               # The following are poor quality types that somehow got through the quality
        - \bWEBSCR\b: {from: title}                           # features usually due to the title including a keyword like "720p" as well
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}                              # The following are groups with poor quality releases
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \[facepalm\]: {from: title}
        - \bASAP\b: {from: title}   
        - \bHDTC\b: {from: title}
        - \bHC\b: {from: title}
        - \bCHINESE\b: {from: title}
    content_size:
      min: 1500
      max: 7500
    seen_movies: 
      scope: local
    inputs:
      - rss: http://extratorrent.cc/rss.xml?type=user&user=condors
      - rss: http://extratorrent.cc/rss.xml?type=user&user=tomcat12
    set:
      movedone: '/home/maxime/media/Movies/English/{{imdb_genres[0]}}/'
      content_filename: '/{{movie_name}} ({{movie_year}}) [{{quality.resolution}}]'
    quality:
      - 720p-1080p
      - bluray
  french-movie:
    proper_movies: yes
    regexp:
      reject:
        - \btruefrench\b: {from: title}
    seen_movies:
      scope: local
    content_size:
      min: 600
      max: 4000
    t411:
      category: Film
      terms:
        - Québécois
        - BDrip/BRrip
        - 2D
    set:
      movedone: '/home/maxime/media/Movies/Francais/{{imdb_genres[0]}}/'
      content_filename: '{{movie_name}} ({{movie_year}}) [{{quality.resolution}}]'
      ratio: 2
      removeatratio: 2
  imdb-movie:
    require_field: imdb_url
    imdb:
      min_score: 5.8
      min_votes: 2500
      reject_genres:
        - musical
  push-bullet:
    notify:
      entries:
        what: accepted
        via:
          - pushbullet:
              api_key : '{? pushbullet.apikey ?}'
  global:
      # Require at least 10 seeds of any torrent
    verify_ssl_certificates: no
    free_space:
      path: /home/maxime/media
      space: 10000
    pathscrub: windows
    deluge:
      main_file_only: yes
      username: '{? deluge.username ?}'
      password: '{? deluge.password ?}'
      host: 'localhost'
      port: 58846
      path: '/home/maxime/media/Downloads/'
      keep_subs: yes
      magnetization_timeout: 30
    regexp:
      reject:
        - \btrailer\b: {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
      reject:
        - '*.wmv'
        - '*CD1*'
        - '*.rar'
        - '*.r0*'
    torrent_alive:
      min_seeds: 10 
    retry_failed:
      max_retries: 5
      retry_time: 2 hours
      retry_time_multiplier: 2
tasks:
  tv-show:
    verify_ssl_certificates: no
    template:
      - global
      - tv
      - push-bullet
  movie-dl:
    template:
      - global
      - imdb-movie
      - movie
      - push-bullet
  french-movie-dl:
    template:
      - global
      - imdb-movie
      - french-movie
      - push-bullet
